services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    container_name: backend_server
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    container_name: frontend_client
    ports:
      - "3000:80"
    depends_on:
      - server
